const S = {
  page:    { fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', padding: "16px 22px", background: "#fff", fontSize: 14, color: "#1d1d1f", maxWidth: 720 },
  title:   { fontSize: 16, fontWeight: 700, marginBottom: 18, paddingBottom: 8, borderBottom: "2px solid #e89520" },
  sl:      { fontSize: 12, fontWeight: 700, color: "#555", textTransform: "uppercase", letterSpacing: "0.4px", marginBottom: 8 },
  section: { marginBottom: 16, padding: "12px 14px", background: "#f9f9f9", border: "1px solid #ebebeb", borderRadius: 7 },
  grid:    { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px 14px", marginBottom: 12 },
  fw:      { display: "flex", flexDirection: "column", gap: 4 },
  fl:      { fontSize: 12, fontWeight: 600, color: "#555" },
  fi:      { width: "100%", padding: "6px 9px", border: "1px solid #d0d0d0", borderRadius: 6, fontSize: 13, outline: "none", background: "#fff", boxSizing: "border-box" },
  fiErr:   { borderColor: "#e05050", background: "#fff8f8" },
  fieldErr:{ fontSize: 11, color: "#c00", marginTop: 2 },
  helpText:{ fontSize: 11, color: "#888", marginTop: -2 },
  wizNav:  { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 18, paddingTop: 14, borderTop: "1px solid #ebebeb" },
  wizBtn:  { padding: "8px 18px", borderRadius: 7, border: "1px solid #d0d0d0", background: "#fff", color: "#333", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  wizDots: { display: "flex", gap: 6, alignItems: "center", justifyContent: "center", margin: "4px 0 14px" },
  wizDot:  { width: 7, height: 7, borderRadius: "50%", background: "#ddd" },
  wizDotOn:{ background: "#0066cc", width: 18, borderRadius: 4 },
  bool:    { display: "flex", alignItems: "center", gap: 7, padding: "4px 0", fontSize: 13, cursor: "pointer" },
  tblWrap: { marginBottom: 12 },
  table:   { width: "100%", borderCollapse: "collapse", fontSize: 12 },
  th:      { padding: "5px 8px", background: "#f5f5f5", border: "1px solid #e0e0e0", fontWeight: 600, textAlign: "left", fontSize: 11, whiteSpace: "nowrap" },
  td:      { padding: "2px 5px", border: "1px solid #f0f0f0" },
  ci:      { width: "100%", border: "none", background: "transparent", fontSize: 12, outline: "none", padding: "3px 4px" },
  addBtn:  { marginTop: 5, padding: "3px 11px", fontSize: 11, color: "#0066cc", background: "none", border: "1px dashed #88aacc", borderRadius: 5, cursor: "pointer" },
  delBtn:  { color: "#bbb", background: "none", border: "none", cursor: "pointer", fontSize: 15, padding: "0 4px", lineHeight: 1 },
  pill:    { padding: "6px 16px", borderRadius: 20, border: "none", background: "#f0f0f0", color: "#444", fontSize: 12, fontWeight: 500, cursor: "pointer", marginRight: 6, marginBottom: 6 },
  pillOn:  { background: "#0066cc", color: "#fff" },
  grpRow:  { display: "flex", alignItems: "center", gap: 8, padding: "4px 0", cursor: "pointer", fontSize: 13 },
  extItem: { border: "1px solid #e5ecf5", borderRadius: 6, padding: "8px 10px", marginBottom: 8 },
  extOpt:  { display: "flex", alignItems: "center", gap: 6, padding: "3px 0", fontSize: 12 },
  badge:   { display: "inline-block", padding: "1px 6px", borderRadius: 100, fontSize: 11, fontWeight: 600, background: "#e8f0fe", color: "#0066cc", marginLeft: 6 },
  sub:     { marginTop: 16, width: "100%", padding: "10px", background: "#0066cc", color: "#fff", border: "none", borderRadius: 7, fontSize: 14, fontWeight: 600, cursor: "pointer" },
  okBox:   { marginTop: 14, padding: 14, background: "#f0faf0", border: "1.5px solid #b2dfb2", borderRadius: 8, color: "#2e7d32" },
  errBox:  { marginTop: 14, padding: 14, background: "#fff0f0", border: "1.5px solid #ffb0b0", borderRadius: 8, color: "#c00", fontSize: 13 },
  dlBtn:   { display: "inline-block", marginTop: 10, marginRight: 8, padding: "7px 16px", background: "#1a6fb5", color: "#fff", border: "none", borderRadius: 6, fontSize: 13, fontWeight: 600, cursor: "pointer", textDecoration: "none" },
  spinner: { display: "inline-block", width: 14, height: 14, border: "2px solid #fff", borderTopColor: "transparent", borderRadius: "50%", verticalAlign: "middle", marginRight: 6, animation: "spin .7s linear infinite" },
};

export default S;
